# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: tanakalucky
# "service" is the name of this project. This will also be added to your AWS resource names.
service: input-attendance-lambda-with-ecr

provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs22.x
  memorySize: 2048
  timeout: 60
  architecture: arm64
  ecr:
    images:
      playwright:
        path: .
        platform: linux/arm64
        provenance: false

functions:
  inputAttendance:
    image: playwright

    environment:
      SENTRY_DSN: ${env:SENTRY_DSN}

    url:
      cors:
        allowedOrigins:
          - '*'
        allowedMethods:
          - POST
        allowedHeaders:
          - Content-Type
          - X-Amz-Date
          - Authorization
          - X-Api-Key
          - X-Amz-Security-Token
        allowCredentials: false
        maxAge: 86400
